name: kronos
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies
  backdrop: ^0.9.1
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  file_picker: ^6.1.1
  youtube_explode_dart: ^2.1.0
  equatable: ^2.0.5
  

  # State 
  flutter_riverpod: ^2.4.10

  # Config
  easy_localization: ^3.0.3

  # Utility
  easy_logger: ^0.0.2
  logger: ^2.0.2+1
  kartal: ^3.5.0
  google_fonts: ^6.1.0

  # Navigation
  auto_route: ^7.8.4

  # Modules
  core:
    path: module/core
  
  gen:
    path: module/gen
  
  common:
    path: module/common
  
  uiwidget:
    path: module/uiwidget


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8
  device_preview: ^1.1.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true



flutter:
  uses-material-design: true

  assets:
    - asset/images/
    - asset/translations/

